#!/usr/bin/env bash
set -euo pipefail

source_ref="${1:-origin/master}"

framework_paths=(
  ".gitignore"
  "agents/author.md"
  "agents/reviewer.md"
  "agents/scout.md"
  "agents/steward.md"
  "scripts/__init__.py"
  "scripts/coverage_map.py"
  "scripts/crawl.py"
  "scripts/drift.py"
  "scripts/file_tickets.py"
  "scripts/flake_tracker.py"
  "scripts/sync_template_paths.sh"
  "scripts/tests/__init__.py"
  "scripts/tests/test_coverage_map.py"
  "scripts/tests/test_crawl.py"
  "scripts/tests/test_drift.py"
  "scripts/tests/test_file_tickets.py"
  "scripts/tests/test_flake_tracker.py"
  "scripts/tests/test_repository_workflows.py"
  ".github/workflows/template-sync.yml"
  ".github/workflows/tests.yml"
  ".claude/agents/reviewer.md"
  ".claude/hooks/pytest-tripwire.sh"
  ".claude/settings.json"
  ".claude/skills/author/SKILL.md"
  ".claude/skills/loop-status/SKILL.md"
  ".claude/skills/scout/SKILL.md"
  ".claude/skills/steward/SKILL.md"
  ".claude/skills/triage/SKILL.md"
  "AGENTS.md"
  "CLAUDE.md"
  "setup.sh"
  ".mcp.json"
  "package.json"
  "pnpm-lock.yaml"
  "pyproject.toml"
  "uv.lock"
  "RULES.md"
  "README.md"
  "docs/spec.md"
  "docs/running-the-loop.md"
  "docs/agents/domain.md"
  "docs/agents/issue-tracker.md"
  "docs/agents/triage-labels.md"
  "dashboard/__init__.py"
  "dashboard/__main__.py"
  "dashboard/server.py"
  "dashboard/snapshot.py"
  "dashboard/ui/app.ts"
  "dashboard/ui/index.html"
  "dashboard/ui/styles.css"
  "dashboard/e2e/current-snapshot.spec.ts"
  "dashboard.playwright.config.ts"
  "tsconfig.dashboard.json"
  "tests/pages/CurrentSnapshotPage.ts"
  "requirements/dashboard/current-snapshot/overview.md"
  "page-maps/dashboard/current-snapshot/page.json"
)

for path in "${framework_paths[@]}"; do
  git rm -r --ignore-unmatch --quiet -- "$path"
  if git cat-file -e "${source_ref}:${path}"; then
    git checkout "$source_ref" -- "$path"
  fi
done
